# Forces new Travis-CI Infrastructure
sudo: false

language: php

addons:
  chrome: stable
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - xvfb
    - fluxbox

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # Composer
  - composer install
  - fluxbox >/dev/null 2>&1 &
  - sleep 3

script:
  - vendor/bin/phing -f build/phing/build.xml
  - mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
  - vendor/bin/robo run:tests --use-htaccess

branches:
  except:
    - K5.0
