name: "Pull Request Labeler"
on:
- pull_request

jobs:
  label:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
